/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mujib.gui;

import com.mujib.MainApps;
import com.mujib.entity.Pembayaran;
import com.mujib.entity.PembayaranManajer;
import com.mujib.entity.Pesanan;
import com.mujib.entity.PesananManajer;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mujibur
 */
public class FormPembayaran extends javax.swing.JFrame {
    
    private MainApps apps;
    private PesananManajer pesananManajer;
    private PembayaranManajer pembayaranManajer;
    Pesanan pesananDitemukan;
    int totalPendapatan = 0;

    DefaultTableModel detailPembayaranTableModel;
    
    /**
     * Creates new form FormPembayaran
     */
    public FormPembayaran() {
        initComponents();
        //pesananManajer = new PesananManajer();
        pembayaranManajer = new PembayaranManajer();
        try {
            populateDetailPembayaranJTable();
        } catch (SQLException ex) {
            Logger.getLogger(FormPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noMejaJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        totalPesananJTextField = new javax.swing.JTextField();
        ppnJTextField = new javax.swing.JTextField();
        uangPembayaranJTextField = new javax.swing.JTextField();
        uangKembaliJTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        strukJTextArea = new javax.swing.JTextArea();
        strukJButton = new javax.swing.JButton();
        bayarJButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        detailPembayaranJTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        totalPendapatanJTextField = new javax.swing.JTextField();
        cariJButton = new javax.swing.JButton();
        infoJLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        closeJMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        pesananJMenuItem = new javax.swing.JMenuItem();
        pembayaranJMenuItem = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PEMBAYARAN");

        jLabel2.setText("NO. MEJA");

        jLabel3.setText("TOTAL PESANAN");

        jLabel4.setText("PPN");

        jLabel5.setText("UANG PEMBAYARAN");

        jLabel6.setText("UANG KEMBALI");

        strukJTextArea.setColumns(20);
        strukJTextArea.setRows(5);
        jScrollPane2.setViewportView(strukJTextArea);

        strukJButton.setText("STRUK");
        strukJButton.setEnabled(false);
        strukJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strukJButtonActionPerformed(evt);
            }
        });

        bayarJButton.setText("BAYAR");
        bayarJButton.setEnabled(false);
        bayarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarJButtonActionPerformed(evt);
            }
        });

        detailPembayaranJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(detailPembayaranJTable);

        jLabel7.setText("TOTAL PENDAPATAN");

        cariJButton.setText("CARI");
        cariJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariJButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        closeJMenuItem.setText("Close");
        closeJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeJMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(closeJMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        pesananJMenuItem.setText("Pesanan");
        pesananJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananJMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(pesananJMenuItem);

        pembayaranJMenuItem.setText("Pembayaran");
        pembayaranJMenuItem.setEnabled(false);
        jMenu2.add(pembayaranJMenuItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(noMejaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addComponent(cariJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalPesananJTextField)
                                    .addComponent(ppnJTextField)
                                    .addComponent(uangPembayaranJTextField)
                                    .addComponent(uangKembaliJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                            .addComponent(strukJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(bayarJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(infoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane4)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(totalPendapatanJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(infoJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(noMejaJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cariJButton))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(totalPesananJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(ppnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(uangPembayaranJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(uangKembaliJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strukJButton)
                    .addComponent(bayarJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalPendapatanJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeJMenuItemActionPerformed
        // TODO add your handling code here:
        this.apps.closeApps();
    }//GEN-LAST:event_closeJMenuItemActionPerformed

    private void pesananJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananJMenuItemActionPerformed
        // TODO add your handling code here:
        this.apps.showFormPesanan();
    }//GEN-LAST:event_pesananJMenuItemActionPerformed

    private void cariJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariJButtonActionPerformed
        // TODO add your handling code here:
        int noMeja = Integer.parseInt(noMejaJTextField.getText());
        PesananManajer pesananManajer = this.apps.getPesananManajer();
        try {
            pesananManajer.populatePesanan();
        } catch (SQLException ex) {
            Logger.getLogger(FormPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pesananDitemukan = pesananManajer.getPesananByNoMeja(noMeja);
        int totalPesanan;
        if (pesananDitemukan != null) {
            totalPesanan = pesananDitemukan.getTotal_pesanan();
        } else {
            totalPesanan = pesananManajer.getTotalPesananByNoMeja(noMeja);
        }
        
        if (totalPesanan != 0) {
            infoJLabel.setText("Data pesanan ditemukan");
            infoJLabel.setForeground(Color.blue);
            totalPesananJTextField.setText(Integer.toString(totalPesanan));
            int ppn = (int) (0.1 * totalPesanan);
            ppnJTextField.setText(Integer.toString(ppn));
            strukJButton.setEnabled(true);
            
        } else {
            infoJLabel.setText("Data pesanan TIDAK DITEMUKAN");
            infoJLabel.setForeground(Color.red);
            strukJButton.setEnabled(false);
            bayarJButton.setEnabled(false);
        }
    }//GEN-LAST:event_cariJButtonActionPerformed

    private void strukJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strukJButtonActionPerformed
        // TODO add your handling code here:
        int totalPesanan = Integer.parseInt(totalPesananJTextField.getText());
        int ppn = (int) (0.1 * totalPesanan);
        int uangPembayaran = Integer.parseInt(uangPembayaranJTextField.getText());
        int uangKembali = uangPembayaran - (totalPesanan + ppn );
        uangKembaliJTextField.setText(Integer.toString(uangKembali));
        String struk = "No Meja: " + noMejaJTextField.getText() + "\n";
        struk += "Total Pesanan: " + totalPesanan + "\n";
        struk += "PPN: " + ppn + "\n";
        struk += "Uang Pembayaran: " + uangPembayaran + "\n";
        struk += "Uang Kembali: " + uangKembali + "\n";
        strukJTextArea.setText(struk);
        
        bayarJButton.setEnabled(true);
    }//GEN-LAST:event_strukJButtonActionPerformed

    private void bayarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarJButtonActionPerformed
        // TODO add your handling code here:
        Pembayaran pembayaran = new Pembayaran();
        pembayaran.setId_pesanan(this.pesananDitemukan.getId_pesanan());
        pembayaran.setNo_meja(this.pesananDitemukan.getNo_meja());
        pembayaran.setTotal_pesanan(this.pesananDitemukan.getTotal_pesanan());
        pembayaran.setPpn(Integer.parseInt(ppnJTextField.getText()));
        pembayaran.setUang_pembayaran(Integer.parseInt(uangPembayaranJTextField.getText()));
        pembayaran.setUang_kembali(Integer.parseInt(uangKembaliJTextField.getText()));
        pembayaran.setStruk(strukJTextArea.getText());
        
        try {
            pembayaranManajer.savePembayaranToDb(pembayaran);
            
            // tandai pesanan sudah dibayar
            pesananManajer.pesananTelahDibayar(pesananDitemukan);
            
            // beri pesan jika simpan database berhasil
            //infoJLabel.setText("Data pembayaran berhasil disimpan.");
            //infoJLabel.setForeground(Color.blue);
            JOptionPane.showMessageDialog(
                    this
                    , "Data pembayaran berhasil disimpan"
                    , "Informasi"
                    , JOptionPane.INFORMATION_MESSAGE
            );
            
            this.resetForm();
            
            detailPembayaranTableModel.fireTableDataChanged();
                        
        } catch (SQLException ex) {
            //infoJLabel.setText("Data pembayaran GAGAL disimpan.");
            //infoJLabel.setForeground(Color.red);
            
            JOptionPane.showMessageDialog(
                    this
                    , "Data pembayaran GAGAL disimpan"
                    , "Terjadi Kesalahan"
                    , JOptionPane.ERROR_MESSAGE
            );
            
            Logger.getLogger(FormPembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bayarJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayarJButton;
    private javax.swing.JButton cariJButton;
    private javax.swing.JMenuItem closeJMenuItem;
    private javax.swing.JTable detailPembayaranJTable;
    private javax.swing.JLabel infoJLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField noMejaJTextField;
    private javax.swing.JMenuItem pembayaranJMenuItem;
    private javax.swing.JMenuItem pesananJMenuItem;
    private javax.swing.JTextField ppnJTextField;
    private javax.swing.JButton strukJButton;
    private javax.swing.JTextArea strukJTextArea;
    private javax.swing.JTextField totalPendapatanJTextField;
    private javax.swing.JTextField totalPesananJTextField;
    private javax.swing.JTextField uangKembaliJTextField;
    private javax.swing.JTextField uangPembayaranJTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the apps
     */
    public MainApps getApps() {
        return apps;
    }

    /**
     * @param apps the apps to set
     */
    public void setApps(MainApps apps) {
        this.apps = apps;
    }

    /**
     * @return the pesananManajer
     */
    public PesananManajer getPesananManajer() {
        return pesananManajer;
    }

    /**
     * @param pesananManajer the pesananManajer to set
     */
    public void setPesananManajer(PesananManajer pesananManajer) {
        this.pesananManajer = pesananManajer;
    }
    
    public void resetForm() {
        noMejaJTextField.setText("");
        totalPesananJTextField.setText("");
        ppnJTextField.setText("");
        uangPembayaranJTextField.setText("");
        uangKembaliJTextField.setText("");
        strukJTextArea.setText("");
    }
    
    public void populateDetailPembayaranJTable() throws SQLException {
        detailPembayaranTableModel = new DefaultTableModel();
        detailPembayaranTableModel.addColumn("No Meja");
        detailPembayaranTableModel.addColumn("Total Pesanan");
        detailPembayaranTableModel.addColumn("PPN");
        detailPembayaranTableModel.addColumn("Uang Pembayaran");
        detailPembayaranTableModel.addColumn("Uang Kembali");
        
        detailPembayaranJTable.setModel(detailPembayaranTableModel);
        
        this.pembayaranManajer.populatePembayaran();
        
        for(Pembayaran pembayaran : this.pembayaranManajer.getDaftarPembayaran()) {
            Object[] detailPembayaran = new Object[5];
            detailPembayaran[0] = pembayaran.getNo_meja();
            detailPembayaran[1] = pembayaran.getTotal_pesanan();
            detailPembayaran[2] = pembayaran.getPpn();
            detailPembayaran[3] = pembayaran.getUang_pembayaran();
            detailPembayaran[4] = pembayaran.getUang_kembali();
            
            detailPembayaranTableModel.addRow(detailPembayaran);
            
            totalPendapatan += pembayaran.getTotal_pesanan();
            totalPendapatanJTextField.setText(Integer.toString(totalPendapatan));
        }
        
    }
}
